export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';
export const SET_FILTERED_RESTAURANTS = 'SET_FILTERED_RESTAURANTS';
export const SET_CITY = 'SET_CITY';
